const name='bhavana';
const rep=50;
console.log(`my name is ${name} and repo is ${rep}`);
const game=new String('hii  hii-all hiii');
console.log(game[0]);
console.log(game.__proto__);
console.log(game.length);
console.log(game.toUpperCase());
console.log(game.charAt(2));
console.log(game.indexOf('h'));
console.log(game.slice(-6,3));
console.log(game.trim());
console.log(game.replace('ii','++'));
console.log(game.split('  '));